import { ThemeProvider } from '@deliciously.cooking/ui'

export const metadata = {
  title: 'Welcome to deliciously.cooking',
  description: 'Generated by create-nx-workspace',
}

interface RootLayoutProps {
  children: React.ReactNode
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}

export default RootLayout
