
export const metadata = {
  title: 'Welcome to deliciously.cooking',
  description: 'Generated by create-nx-workspace',
}

interface RootLayoutProps {
  children: React.ReactNode
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body>

        {children}

      </body>
    </html>
  )
}

export default RootLayout
